### ISSUE TITLE
Issue with rhoReactingCentralFoam

### ISSUE THREAD

**Issue by jomarchris** [Keivan-A-Gh/Master_Thesis#1]
Followed the manual for setting up the updated rhoReactingCentralFoam solver. We are having issues when starting rhoReactingCentralFoam on the demo case.

What we did:

1. Copied "applications" and "src" folders to our user folder.
2. Did ./Allwmake on rhoReactingCentralFoam
3. Did wmake on src/basic, reactionThermo, then specie.
4. Ran blockMesh, setFields on demo. rhoReactingCentralFoam gives following error.

![image](https://github.com/Keivan-A-Gh/Master_Thesis/assets/96499758/bf121845-7197-4379-b6ab-928f527cc8d9)

**Comment by jomarchris** [comment]
We found the issue in the "Make/files". There's a case type. reactions should be Reactions

![image](https://github.com/Keivan-A-Gh/Master_Thesis/assets/96499758/997e9826-f630-402d-a891-d535cd3f85c5)

**Comment by Keivan-A-Gh** [comment]
> We found the issue in the "Make/files". There's a case type. reactions should be Reactions
> 
> ![image](https://user-images.githubusercontent.com/96499758/276332639-997e9826-f630-402d-a891-d535cd3f85c5.png)

Hi Jomarchris

First of all, thank you for your cooperation. 
I am not sure on which version you have tried to compile these codes, but on OpenFOAM v7, the directories were exactly as I wrote in the `Make/files`. If you are interested, you can check that out at the following link:
https://cpp.openfoam.org/v7/dir_8e13188b11d4c55bfed76418f20cd2bc.html

Kind regards,
Keivan

**Comment by WangS195** [comment]
Hi @jomarchris  I am very fortunate to see your comment. I have the same issue. May I ask how you solved it?

Best wishes,
Wang
